export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"63e6574e4a50a9001ffd1092"
			]
		},
		"63e6574e4a50a9001ffd1092": {
			"id": "63e6574e4a50a9001ffd1092",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {},
		"seo": {
			"favicon_apple_152px": "url(../images/logo.png)",
			"favicon_32px": "url(../images/logo.png)",
			"favicon_win10_270px": "url(../images/logo.png)",
			"og:title": "Nephro AI — Discovering Health",
			"og:description": "Revolutionize your nephrological disease diagnosis with our cutting-edge AI technology.",
			"og:image": "url(../images/logo.png)",
			"title": "Nephro AI — Discovering Health",
			"description": "Revolutionize your nephrological disease diagnosis with our cutting-edge AI technology.",
			"sitemapFileType": "autogenerated"
		}
	}
}